# Setup
title:        lim1ts' homepage
tagline:      An newbie's journey into Security and Networks
extras:       New posts every week!
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       TS Lim
  url:        https://github.com/lim1ts 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
